-- Seed Market Indices (Casablanca Stock Exchange indices)
-- V4__seed_market_indices.sql

INSERT INTO market_schema.market_indices 
(code, name, market_place, index_type, price, date_price, created_at, updated_at)
VALUES
-- Main Indices
('MASI', 'Moroccan All Shares Index', 'CSE', 'MAIN', 13500.00, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('MADEX', 'Moroccan Most Active Shares Index', 'CSE', 'MAIN', 11000.00, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

-- Sector Indices
('MASI.BC', 'MASI Banks', 'CSE', 'SECTOR', 8500.00, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('MASI.TC', 'MASI Telecommunications', 'CSE', 'SECTOR', 9200.00, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('MASI.IM', 'MASI Real Estate', 'CSE', 'SECTOR', 7800.00, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('MASI.AS', 'MASI Insurance', 'CSE', 'SECTOR', 6900.00, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('MASI.MC', 'MASI Building Materials', 'CSE', 'SECTOR', 5600.00, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('MASI.EN', 'MASI Energy', 'CSE', 'SECTOR', 4800.00, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('MASI.AG', 'MASI Agribusiness', 'CSE', 'SECTOR', 5200.00, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

-- Size-based Indices
('MASI.20', 'MASI 20', 'CSE', 'SIZE', 12000.00, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('MASI.ESG', 'MASI ESG', 'CSE', 'ESG', 10500.00, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

-- Create unique constraint on code if not exists
CREATE UNIQUE INDEX IF NOT EXISTS idx_indices_code_unique ON market_schema.market_indices(code);
